# Generated by Django 5.1.15 on 2025-12-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('chapter', models.IntegerField()),
                ('verse', models.IntegerField()),
                ('kjv_text', models.TextField(verbose_name='King James Version')),
                ('ethiopian_text', models.TextField(verbose_name='Ethiopian/Gnostic Text')),
                ('analysis', models.TextField(blank=True, help_text='Ministry reflection on the difference')),
            ],
            options={
                'ordering': ['book_title', 'chapter', 'verse'],
            },
        ),
    ]
