# Generated by Django 5.1.15 on 2025-12-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripturecomparison',
            name='kjv_text',
            field=models.TextField(blank=True, verbose_name='King James Version'),
        ),
    ]
